source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'HelloGold' do
    pod 'Alamofire', '~> 4.7'
    pod 'ObjectMapper', '~> 3.5'
    pod 'PromiseKit', '~> 6.8'
end

